# -*- coding: utf-8 -*-
"""TinyImageNetLoader.ipynb
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1-YNINYX9aH6Pk3XBNaJqbl86H8eC2yO9

    From https://github.com/pranavphoenix/TinyImageNetLoader/blob/main/tinyimagenetloader.py
"""

# loads images as 3*64*64 tensors

# !wget http://cs231n.stanford.edu/tiny-imagenet-200.zip
# !unzip -q tiny-imagenet-200.zip


# transform = transforms.Normalize(
#     (122.4786, 114.2755, 101.3963), (70.4924, 68.5679, 71.8127)
# )

# trainset = TrainTinyImageNetDataset(id=id_dict, transform=transform)
# trainloader = torch.utils.data.DataLoader(
#     trainset, batch_size=batch_size, shuffle=True, num_workers=2
# )

# testset = TestTinyImageNetDataset(id=id_dict, transform=transform)
# testloader = torch.utils.data.DataLoader(
#     testset, batch_size=batch_size, shuffle=False, num_workers=2
# )
